CREATE USER IF NOT EXISTS 'debezium'@'%' IDENTIFIED BY 'debezium-dev';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, LOCK TABLES ON *.* TO 'debezium'@'%';
FLUSH PRIVILEGES;
