CREATE TABLE term_catalog (
  term_id BIGINT PRIMARY KEY,
  frozen BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
INSERT INTO term_catalog (term_id, frozen) VALUES (202601, FALSE);
